server:
  port: 60000
jwt:
  header: Authorization
  #  token 的密钥
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # token有效时间为24小时
  token-validity-in-seconds: 86400
file:
  avatar: D:\\yxyUser\\avatar\\
  sharePicture: D:\\sharePicture\\